### ISSUE TITLE
smbpasswd creation not happening

### ISSUE THREAD

**Issue by joshzitting** [sous-chefs/samba#26]
I am having issues with this cookbook.. it is creating the users just fine and the shares etc but It is NOT setting the smbpasswds.. when I run a `sudo pdbedit -L -v` the password last set is set to a 0. if I manually set the password with `smbpasswd -a jtest`, it updates password last set to a date.... I have set up my users data bag as described in the docs and have tested to make sure that the users variable (in server.rb) is being set.. 

```
Unix username:        joshzitting
Password last set:    0
# smbpasswd -a joshzitting
New SMB password:
Retype new SMB password:
# sudo pdbedit -L -v
Unix username:        joshzitting
Password last set:    Tue, 20 Jan 2015 21:39:20 UTC

after I create my password manually I can log into the shares etc. 
Here is a user DBI 
{
  "id": "joshzitting",
  "smbpasswd": "test"
}
```

The users are created on the machine prior to running the samba::server recipe. 
Thanks! 
Josh

**Comment by ant0ine** [comment]
I confirm, I have the same issue. Reading the code, I think the :enable step should be passing the password on STDIN like the :create step does. If I run the enable step manually with the password, it works.

**Comment by ant0ine** [comment]
Actually, there is more than that. The `:create` step is never executed. Something else is creating the entry before the user provider. After a `sudo smbpasswd -x <username>`, chef creates the entry correctly.

**Comment by ant0ine** [comment]
ok, this is the ubuntu samba package that as part of the post-install setup creates entry in the samba user database. This explains why the recipe finds an existing entry, and skips the `:create` step.

**Comment by Rud5G** [comment]
Perhaps we need to update the user resource, to be able to identify and handle the samba users with password which were never set.

**Comment by damacus** [comment]
I'm going to close this issue for now as it's been open for nearly 2 years. 

If it's still present I'd love to get some tests around this.
