### ISSUE TITLE
create a custom resource samba_share

### ISSUE THREAD

**Issue by jtimberman** [sous-chefs/samba#35]
The resource will be responsible for:
- [x] Creating the directory for the share
- [x] Appending the configuration to an accumulator for /etc/samba/smb.conf

**Comment by gggeek** [comment]
Am I correct in understanding that is still to be implemented?

This is currently a bit of a pain in the neck for me, as I am using Vagrant with chef-solo, and apparently adding support for data-bags (I had none in my cookbook so far) has some consequences... for the moment I get an error 'I cannot read /etc/chef/client.pem, which you told me to use to sign requests!'

**Comment by jtimberman** [comment]
Correct, this is not implemented. I wanted to open the issue in case someone has cycles to work on this, as I don't.

**Comment by jtimberman** [comment]
As for your issue, I recommend using chef-client with local mode rather than chef-solo - particularly for cookbooks like this one that rely on data bags.
