### ISSUE TITLE
Creating a samba user resets the user password if the user already exists.

### ISSUE THREAD

**Issue by starx** [sous-chefs/samba#63]

**Comment by damacus** [comment]
This is pretty much the intended behaviour as it uses the chef `user` resource under the good (which takes over maintaining the user).

1) We can throw some documentation together for this
2) Add a `manage_user` switch and default it to true.

**Comment by starx** [comment]
@damacus Yeah, it seems like intended behavior, but I was thinking this was done the way it is because the team wanted the user to create a specific user for samba purposes. 

However, if it is trying to manage the user itself which is already created manually or through another cookbook then that I think is wrong. Because the control over a create/update action on a user should be up to the user. It's a not an odd case that a system user has different system password and samba password. This cookbook should only be concerned about creating server/client/user for samba.

If you look at the code right now, it skips the code to create samba user and defaults to using system user. 

Not to mention, `user` resource can take a  encrypted password and set that, whereas this cookbook does not, forcing the user to pass unencrypted text password and if it sets the password for the system user as well, then it is exposing both the password. 

Adding `manage_user` switch would work, but I would suggest to not touch the system user at all.

**Comment by damacus** [comment]
>However, if it is trying to manage the user itself which is already created manually or through another cookbook then that I think is wrong. Because the control over a create/update action on a user should be up to the user. It's a not an odd case that a system user has different system password and samba password. This cookbook should only be concerned about creating server/client/user for samba.

Thanks for the feedback @starx I'm considering adding in the `manage_user` switch. But defaulting it to true. 
- Managing users manually isn't ever a good pattern. 
- This cookbook should be able to create everything it needs to get up and running (smb users require a local user) 

The smb user block is notified when creating the user resource (`notifies :run, "execute[Create samba user #{new_resource.name}]", :immediately` ) so that we don't run this every time. As a result unless you can think of a good way to add the smb_user idempotently (and not reset the password every run) then we'll go with that. 

Feel free to drop on the #sous-chefs Slack channel on the [chefcommunity](chefcommunity.slack.com) slack

**Comment by damacus** [comment]
Alternatively (and probably preferred in your case), you can leave the `samba_user` resource and make your own, that is idempotent on your own system.

**Comment by starx** [comment]
@damacus Do you really need to close this saying make your own resource? I strongly believe overriding the user password that's been generated before while adding a samba user is not an expected behavior from this cookbook.

**Comment by Jamedjo** [comment]
> This cookbook should be able to create everything it needs to get up and running (smb users require a local user)

> ... unless you can think of a good way to add the smb_user idempotently

How about checking if the system user already exists first? That would avoid replacing an existing user while allowing new users to be created.

**Comment by damacus** [comment]
Sounds like a plan @Jamedjo fancy submitting a PR for the functionality?

**Comment by damacus** [comment]
So right now we have a switch for don't manage user homes. 

This functionality is getting pretty close to "please don't manage the user I put on the box", but do manage the smbuser. 

We can go two ways here:
- Put a switch in to not manage the user at all (an extension of the `manage_home` functionality)
- Don't ever manage the non-smb side of things and error out with a fatal if the user doesn't put the user on the box itself.

How are you'all getting the users on the box without Chef right now?

**Comment by damacus** [comment]
We'll continue this discussion over at #72 as it's a little clearer what we're trying to achieve. `Creating a samba user resets the user password if the user already exists` is actually the intended behaviour, right now.
