### ISSUE TITLE
Chef version 12.15 needed due to undefined method `delayed_action'

### ISSUE THREAD

**Issue by Jamedjo** [sous-chefs/samba#73]
The below error broke things for me, which was solved by updating to a version which includes https://github.com/chef/chef/commit/bb9a4d31ed5864e00b5379f6b69acb2dc6588133. I think the readme might need updating to show `12.15+` as the minimum version.

```
================================================================================
    Error executing action `create` on resource 'samba_server[samba server]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `delayed_action' for Chef::Resource::Template
```

**Comment by damacus** [comment]
Thanks! 
It's often hard to dig out those API changes.

**Comment by damacus** [comment]
Fancy submitting a PR for the metadata & README changes?

**Comment by damacus** [comment]
This is actually in the metadata, chef version 12.16 is required. You *should* be getting an error for the chef-client not being the required version.

**Comment by adhodgson1** [comment]
Sorry didn't look in the metadata, just the Readme where it states:

### Chef

- Chef 12.15+

Chef-Client didn't complain about the wrong Chef version being used for some reason, but the quick Google came up with this issue fairly quickly, and moving to Chef 12.16 fixed the issue fine.
