### ISSUE TITLE
Unable to use computer after password overwritten

### ISSUE THREAD

**Issue by Jamedjo** [sous-chefs/samba#74]
Using the `samba_user` overwrites a user's password, quite unexpectedly. I also don't think this is the default behaviour in samba. Additionally, using the password I set there doesn't work either, so I have no idea what it has been set to. 

I'm **now unable to sudo**, unable to run chef, and would be unable to ssh in if I wasn't using keys.

```
[2017-07-23T20:23:10+01:00] INFO: linux_user[myuser] altered

      - alter user myuser
[2017-07-23T20:23:10+01:00] INFO: linux_user[myuser] sending run action to execute[Create samba user myuser] (immediate)
    * execute[Create samba user myuser] action run[2017-07-23T20:23:10+01:00] INFO: Processing execute[Create samba user myuser] action run (/home/myuser/chef-solo/local-mode-cache/cache/cookbooks/samba/resources/user.rb line 59)

      [execute] Added user myuser.
[2017-07-23T20:23:10+01:00] INFO: execute[Create samba user myuser] ran successfully
      - execute echo 'mypassword
      mypassword' | smbpasswd -s -a myuser
    * group[myuser] action create[2017-07-23T20:23:10+01:00] INFO: Processing group[myuser] action create (/home/myuser/chef-solo/local-mode-cache/cache/cookbooks/samba/resources/user.rb line 48)
[2017-07-23T20:23:10+01:00] INFO: group[myuser] altered

      - alter group myuser
      - replace group members with new list of members
```

It looks like the version which installed is `1.0.4`:
```
cat Cheffile.lock | grep samba
    samba (1.0.4)
```

Related: https://github.com/sous-chefs/samba/issues/63

**Comment by damacus** [comment]
Closing as a duplicate issue #63 #72

**Comment by damacus** [comment]
Hey @Jamedjo come grab us on the Chef community Slack tomorrow. Sounds like you might be having some wider issues with your use of Chef?

**Comment by josephholsten** [comment]
@Jamedjo yes, please get ahold of us. Sounds like a very bad day, we're really want to help. If you aren't on the slack already, you can sign up at http://community-slack.chef.io/.
