### ISSUE TITLE
bind_interfaces_only does nothing in samba_server resource

### ISSUE THREAD

**Issue by Sam-Martin** [sous-chefs/samba#85]
# Scenario

```
samba_server 'test_server" do
  workgroup 'samba'
  interfaces 'eth0'
  bind_interfaces_only 'yes'
end
```

# Expected result
```
# grep bind /etc/samba/smb.conf
# bind interfaces only = yes
```

# Actual result
```
# grep bind /etc/samba/smb.conf
#
```

# Cause
Looking at [resources/server.rb](https://github.com/sous-chefs/samba/blob/master/resources/server.rb) the `bind_interfaces_only` property is defined, but nothing is done with it. Also the tests don't seem to look to see if the value is set, so it seems plausible that this simply doesn't work?

I may have missed something super obvious, so if I have, I apologise!

**Comment by damacus** [comment]
Fixed as part of #86
